const ADD_ITEM = 'ADD_ITEM';
const REMOVE_ITEM = 'REMOVE_ITEM';
const EDIT_ITEM = 'EDIT_ITEM';
const CLEAR_ITEMS = 'CLEAR_ITEMS';
const UPDATE_INPUT = 'UPDATE_INPUT';
const CLOSE_STATUS = 'CLOSE_STATUS';


export { ADD_ITEM, REMOVE_ITEM, EDIT_ITEM, CLEAR_ITEMS, UPDATE_INPUT, CLOSE_STATUS }